@echo off
echo deleting image files (*.tif, *.tiff, *.jpg, *.jpeg)
echo ....
recycle -f *.tif
echo ........
recycle -f *.tiff
echo ............
recycle -f *.jpg
echo ................
recycle -f *.jpeg
echo images recycled!!!
pause
