#! /bin/bash

# This is comment

echo "The current directory is:"
pwd
echo "The user logged in is:"
whoami

echo "Home for the current user is: $HOME"
echo "I have $1 in my pocket"

grade=5
person="Adam"
echo "$person is a good boy, he is in grade $grade"

# command substitution, result of command to variable
mydir=`pwd`
mydir1=$(pwd)
echo $mydir
echo $mydir1

var1=$(( 5 + 5 ))
echo $var1
var2=$(( $var1 * 2 ))
echo $var2

user="anotherUser"
if grep $user /etc/passwd
then
  echo "The user $user Exists"
elif ls /home
then
  echo "The user doesn’t exist"
fi

num=11
if [ $num -gt 10 ]
then
echo "$num is bigger than 10"
else
echo "$num is less than 10"
fi

v1="text"
v2="another text"
if [ $v1 \> "$v2" ]
then
echo "$v1 is greater than $v2"
else
echo "$v1 is less than $v2"
fi
