abs
!anfang ______________________________abs_____________________________________________
	!in case abbreviations are erased
	!*abbr,abs,*use,abs
	*abbr,ec1,*use,ec1
	*abbr,ec0,*use,ec0
	*abbr,ac0,*use,ac0
	*abbr,ac1,*use,ac1
	*abbr,estt,*use,estt
	*abbr,esn,*use,esn
	*abbr,cdir,*use,cdir
	*abbr,cg,*use,cg
	*abbr,bnode,*use,bnode
	*abbr,dp,*use,dp
	*abbr,dls,*use,dls
	!*abbr,avg,*use,gtAvg
	!*abbr,nodeInfo,*use,nodeInfo -------------------- use nInfo Macro
	!*abbr,elemInfo,*use,elemInfo --------------------------use eInfo Macro
	*abbr,solids,*use,solids
	*abbr,conts,*use,conts
	*abbr,federn,*use,federn
	*abbr,shells,*use,shells
	*abbr,surfs,*use,surfs
	*abbr,lines,*use,lines
	*abbr,noCont,*use,noCont
	!*abbr,anno4modified,*use,anno4modified
	*abbr,plotFKN,*use,plotFKN
	!*abbr,plotMat,*use,plotMat
	*abbr,matPlot,*use,matPlot
	*abbr,solFy,*use,solFy
	!*abbr,plotFy,*use,plotFy
	*abbr,bdPlot,*use,bdPlot
	*abbr,baPlot,*use,baPlot
	*abbr,laPlot,*use,laPlot
	!*abbr,ano3d,*use,ano3d
	!abbr,Chr2sec,*use,Chr2sec
	!*abbr,r2sec,*use,r2sec
	*abbr,smisc1,*use,smisc1
	*abbr,nmisc1,*use,nmisc1
	!*abbr,pl7sm,*use,pl7sm
	*abbr,wpy,*use,wpy
	*abbr,wpn,*use,wpn
	*abbr,epll,*use,epll
	!*abbr,di78sm,*use,di78sm		!Thickness according to Section Type
	!*abbr,di78all,*use,di78all		!Thickness according to Section Type
	*abbr,cp7,/inp,cp7,mac,E:\__CoreE\
	!*abbr,plotsm,/inp,pl7sm,mac,E:\__CoreE\
!ende _____________________________________________________________________________
/eof
ec0
!*ulib,sm,mac,E:
!anfang ______________________________ec0_____________________________________________
!show element vectors
/psymb,esys,0
eplo
!ende _____________________________________________________________________________
/eof
ec1
!anfang _______________________________ec1____________________________________________
!show element vectors
/psymb,esys,1
eplo
!ende _____________________________________________________________________________
/eof
ac0
!anfang _______________________________ac0____________________________________________
!show element vectors
/psymb,adir,0
aplo
!ende _____________________________________________________________________________
/eof
ac1
!anfang _______________________________ac1____________________________________________
!show element vectors
/psymb,adir,1
aplo
!ende _____________________________________________________________________________
/eof
estt
!anfang _________________________________estt__________________________________________
!auswählen von TargetElemente (ohne Targetfläche)
!arg1, arg2: real des Kontakflächenpaares
esel,s,real,,arg1,arg2
esel,r,ename,,170
nsle
!eplo
!ende _____________________________________________________________________________
/eof
cg
!anfang _______________________________________cg____________________________________
!Calculate C.G. of selection

*get,tmCount,node,,count
*get,nodeMin,node,,num,min

xsum=0
ysum=0
zsum=0

*do,i,1,tmCount
	xsum=xsum+nx(nodeMin)
	ysum=ysum+ny(nodeMin)
	zsum=zsum+nz(nodeMin)
	*get,nodeMin,node,nodeMin,nxth
*enddo

xsum=xsum/tmCount
ysum=ysum/tmCount
zsum=zsum/tmCount

!*msg,,xsum,ysum,zsum
!C.G. = %G , %G, %G
/com,
/com, C.G. : %xsum%, %ysum%, %zsum%
/com,

spoint,,xsum,ysum,zsum

!ende _______________________________________name____________________________________
/eof
bnode
!anfang _______________________________________bnode____________________________________

esel,s,ename,,188
nsle

*if,arg1,eq,1,then
	*if,arg2,eq,1,then
		*get,nMin,node,,mxloc,x
	*else
		*get,nMin,node,,mnloc,x
	*endif
	nsel,r,loc,x,nMin
*elseif,arg1,eq,2,then
	*if,arg2,eq,1,then
		*get,nMin,node,,mxloc,y
	*else
		*get,nMin,node,,mnloc,y
	*endif
	nsel,r,loc,y,nMin
*else
	*if,arg2,eq,1,then
		*get,nMin,node,,mxloc,z
	*else
		*get,nMin,node,,mnloc,z
	*endif
	nsel,r,loc,z,nMin
*endif

/pbc,nfor,,1
nplo
fsum

!ende _______________________________________name____________________________________
/eof
dp
!anfang _______________________________________dp____________________________________
	/sys,del *.jpg
	/sys,del *.tif
	/sys,del *.tiff
	/sys,del *.png
!ende _______________________________________name____________________________________
/eof
!gtAvg
!!anfang _______________________________________gtAvg____________________________________
	!*get,max_y,node,,mxloc,y
	!*get,min_y,node,,mnloc,y
	!*get,max_z,node,,mxloc,z
	!*get,min_z,node,,mnloc,z
	!*get,max_x,node,,mxloc,x
	!*get,min_x,node,,mnloc,x
	!avg_x=(max_x+min_x)/2
	!avg_y=(max_y+min_y)/2
	!avg_z=(max_z+min_z)/2
!ende _______________________________________name____________________________________
!/eof
!nodeInfo
!!anfang _______________________________________nodeInfo____________________________________
	!*get,nmaxd,node,,num,maxd
	!*get,nmax,node,,num,max
	!*get,nmin,node,,num,min
	!*get,nanz,node,,count
!!ende _______________________________________name____________________________________
!/eof
!elemInfo
!!anfang _______________________________________elemInfo____________________________________
	!*get,emaxd,elem,,num,maxd
	!*get,emax,elem,,num,max
	!*get,emin,elem,,num,min
	!*get,eanz,elem,,count
!!ende _______________________________________name____________________________________
/eof
solids
!anfang _______________________________________solids____________________________________
	*if,arg1,lt,1,then
		esel,none
	*endif
	esel,a,ename,,185,187
	esel,a,ename,,5
	esel,a,ename,,65
	esel,a,ename,,70
	esel,a,ename,,87
	esel,a,ename,,90
	esel,a,ename,,96,98
	esel,a,ename,,122,123
	esel,a,ename,,164
	esel,a,ename,,168
	esel,a,ename,,226,227
	esel,a,ename,,231,232
	esel,a,ename,,236,237
	esel,a,ename,,239,240
	esel,a,ename,,272,279
	nsle
!eplo
!ende _______________________________________name____________________________________
/eof
conts
!anfang _______________________________________conts____________________________________
	*if,arg1,lt,1,then
		esel,none
	*endif
	esel,a,ename,,170,178
	nsle
	eplo
!ende _______________________________________name____________________________________
/eof
shells
!anfang _______________________________________shells____________________________________
	*if,arg1,lt,1,then
		esel,none
	*endif
	esel,a,ename,,181
	nsle
	!eplo
!ende _______________________________________name____________________________________
/eof
federn
!anfang _______________________________________name____________________________________
	*if,arg1,eq,0,then
		esel,s,ename,,14
	*else
		esel,a,ename,,14
	*endif
	nsle
	eplo
!ende _______________________________________name____________________________________
/eof
lines
!anfang _______________________________________lines____________________________________
	*if,arg1,eq,0,then
		esel,none
	*endif
	*if,arg2,eq,0,then
		esel,a,ename,,180
	*endif
	esel,a,ename,,188
	nsle
	eplo
!ende _______________________________________name____________________________________
/eof
surfs
!anfang _______________________________________surfs____________________________________
	esel,s,ename,,151,155
	nsle
	eplo
!ende _______________________________________name____________________________________
/eof
noCont
!anfang _______________________________________noCont____________________________________
	esel,u,ename,,170,175
	nsle
	eplo
!ende _______________________________________name____________________________________
/eof
anno4modified
!anfang _______________________________________anno4modified____________________________________
	!Erstellt Uradial Plot mit 3D-Notation für Firste,Ulme,Sohle
	!arg1= z-Koordinate
	!arg2= Skalierfaktor für Uradial Plot

	!/tspec,,0.25!14

	csys
	*get,maxy,node,,mxloc,y
	*get,miny,node,,mnloc,y
	*get,maxx,node,,mxloc,x
	!arg1=zl25

	n1= node(0,maxy,arg1)
	*stat,n1
	nx1= nx(n1)
	ny1= ny(n1)
	nz1= nz(n1)

	n2= node(0,miny,arg1)
	*stat,n2
	nx2= nx(n2)
	ny2= ny(n2)
	nz2= nz(n2)

	n3= node(maxx,0,arg1)
	*stat,n3
	nx3= nx(n3)
	ny3= ny(n3)
	nz3= nz(n3)

	*if,arg3,lt,1,then
		*do,i,1,3,1
			uxi = ux(n%i%)
			uyi = uy(n%i%)
			uzi = uz(n%i%)

			uri = sqrt(uxi**2+uyi**2)
			urneu= 1000*uri
			urneuu=nint(urneu)
			uri = urneuu/1000

			uxneu= 1000*uxi
			uxneuu=nint(uxneu)
			uxi = uxneuu/1000

			*if,arg2,ge,1,then
				scal = arg2
			*elseif,arg2,lt,1,then
				scal = 1
			*endif

			*if,i,eq,1,then
				/AN3D,ANUM,0,105,nx%i%,ny%i%,nz%i%
				/an3d,ARR2,1,nx%i%,ny%i%,nz%i%,nx%i%+uxi*scal,ny%i%+uyi*scal,nz%i%+uzi*scal
				/an3d,TEXT,nx%i%+uxi*scal*1.1-maxx/3,ny%i%+uyi*scal,nz%i%+uzi*scal ,UX= %uri%
			*elseif,i,eq,2,then
				/AN3D,ANUM,0,105,nx%i%,ny%i%,nz%i%
				/an3d,ARR2,1,nx%i%,ny%i%,nz%i%,nx%i%+uxi*scal,ny%i%+uyi*scal,nz%i%+uzi*scal
				/an3d,TEXT,nx%i%+uxi*scal-maxx/3,ny%i%+uyi*scal,nz%i%+uzi*scal ,UX= %uri%
			*elseif,i,eq,3,then
				/AN3D,ANUM,0,105,nx%i%,ny%i%,nz%i%
				/an3d,ARR2,1,nx%i%,ny%i%,nz%i%,nx%i%+uxi*scal,ny%i%+uyi*scal,nz%i%+uzi*scal
				/an3d,TEXT,nx%i%+uxi*scal*1.1,ny%i%+uyi*scal,nz%i%+uzi*scal ,UX= %uxi%
			*endif
		*enddo
	*elseif,arg3,eq,1,then
		*do,i,1,3,1
			*if,i,ne,3,then
				rsys
				uxi = ux(n%i%)
				uyi = uy(n%i%)
				uzi = uz(n%i%)
			*elseif,i,eq,3,then
				rsys,1
				uxi = ux(n%i%)
				uyi = uy(n%i%)
				uzi = uz(n%i%)
				rsys
			*endif

			uri = sqrt(uxi**2+uyi**2)

			urneu= 1000*uri
			urneuu=nint(urneu)
			uri = urneuu/1000

			uxneu= 1000*uxi
			uxneuu=nint(uxneu)
			uxi = uxneuu/1000

			*if,arg2,ge,1,then
				scal = arg2
			*elseif,arg2,lt,1,then
				scal = 1
			*endif

			*if,i,eq,1,then
				/AN3D,ANUM,0,105,nx%i%,ny%i%,nz%i%
				/an3d,ARR2,1,nx%i%,ny%i%,nz%i%,nx%i%+uxi*scal,ny%i%+uyi*scal,nz%i%+uzi*scal
				/an3d,TEXT,nx%i%+uxi*scal*1.1-maxx/3,ny%i%+uyi*scal,nz%i%+uzi*scal ,UX= %uri%
			*elseif,i,eq,2,then
				/AN3D,ANUM,0,105,nx%i%,ny%i%,nz%i%
				/an3d,ARR2,1,nx%i%,ny%i%,nz%i%,nx%i%+uxi*scal,ny%i%+uyi*scal,nz%i%+uzi*scal
				/an3d,TEXT,nx%i%+uxi*scal-maxx/3,ny%i%+uyi*scal,nz%i%+uzi*scal ,UX= %uri%
			*elseif,i,eq,3,then
				/AN3D,ANUM,0,105,nx%i%,ny%i%,nz%i%
				/an3d,ARR2,1,nx%i%,ny%i%,nz%i%,nx%i%+uxi*scal,ny%i%+uyi*scal,nz%i%+uzi*scal
				/an3d,TEXT,nx%i%+uxi*scal*1.1,ny%i%+uyi*scal,nz%i%+uzi*scal ,UX= %uxi%
			*endif
		*enddo
	*endif

	rsys,1
	/dsc,,scal
	plns,u,x,1,1
	rsys,0

	maxy=
	miny=
	maxx=
!ende _______________________________________name____________________________________
/eof
plotFKN
!anfang _______________________________________plotFKN____________________________________
!nur in Post1 !
*get,rou_,active,,rout
*if,rou_,eq,31,then

	/nopr
	/plopts,info,on
	tsize_=0.8
	/tspec,15,tsize_,1,0,0
	/anno,tmod,1
	/anum,1

	cm,ee_,elem
	cm,nn_,node

	!deutsch / englisch
	*if,englisch_,lt,0.001,then
		englisch_=0
	*endif

	r1_=500
	*set,vc2_
	*dim,vc2_,,r1_

	cmsel,s,ee_
	rCount=0
	*do,i,1,r1_,
		
		*get,eanz_,elem,,count
		*if,eanz_,le,0,then
			*exit
		*endif

		*get,emin_,elem,,num,min
		*get,rnum_,elem,emin_,attr,real
		*get,fknv_,rcon,rnum_,const,3			!for FKN
		fknv_=-1*fknv_*1000
		
		add=1
		*do,j,1,i-1
			*if,vc2_(j),eq,fknv_,then
				add=0
			*endif
		*enddo
		
		*if,add,eq,1,then
			rCount=rCount+1
			vc2_(rCount)=fknv_
		*endif

		esel,u,real,,rnum_

	*enddo

	!Elementdicken sortieren
	*do,i,1,rCount-1
		*do,j,i+1,rCount
			*if,vc2_(i),gt,vc2_(j),then
				ii=vc2_(i)
				vc2_(i)=vc2_(j)
				vc2_(j)=ii
			*endif
		*enddo
	*enddo

	cmsel,s,ee_
	*get,emin_,elem,,num,min
	*get,emax_,elem,,num,max
	*get,eanz_,elem,,count

	*set,vec_
	*dim,vec_,,emax_
	etable,ddd,smisc,1

	ii=emin_
	*do,i,1,eanz_
		*get,rc1_,elem,ii,attr,real
		*get,rreal_,rcon,rc1_,const,3			!for FKN

			vec_(ii)=-rreal_*1000
			!vec_(ii)=14

		*get,ii,elem,ii,nxth
	*enddo

	*vput,vec_(1),elem,1,etab,ddd

	nv=rCount
	*if,nv,eq,0,then
		/cval,1,
	*elseif,nv,eq,1
		/cval,1,vc2_(1)
	*elseif,nv,eq,2
		/cval,1,vc2_(1),vc2_(2)
	*elseif,nv,eq,3
		/cval,1,vc2_(1),vc2_(2),vc2_(3)
	*elseif,nv,eq,4
		/cval,1,vc2_(1),vc2_(2),vc2_(3),vc2_(4)
	*elseif,nv,eq,5
		/cval,1,vc2_(1),vc2_(2),vc2_(3),vc2_(4),vc2_(5)
	*elseif,nv,eq,6
		/cval,1,vc2_(1),vc2_(2),vc2_(3),vc2_(4),vc2_(5),vc2_(6)
	*elseif,nv,eq,7
		/cval,1,vc2_(1),vc2_(2),vc2_(3),vc2_(4),vc2_(5),vc2_(6),vc2_(7)
	*else
		/cval,1,vc2_(1),vc2_(2),vc2_(3),vc2_(4),vc2_(5),vc2_(6),vc2_(7),vc2_(nv)
	*endif

	/anno,dele
	/tlabel, +1.040,-0.98,Contact Normal Stiffness

	/anno,refr
	pletab,ddd
	/anno,dele
	/cval
	/go

	*set,vec_
	*set,vc2_
*endif
!ende _______________________________________name____________________________________
/eof
ano3d
!anfang _______________________________________an03d____________________________________
!Need to give co-ordinates from arg1 to arg6 first
!	n1x n1y n1z n2x n2y n2z
!Erstellt 3D-Notation
	!arg1= x-Koordinate 1
	!arg2= y-Koordinate 1
	!arg3= z-Koordinate 1
	!arg4= x-Koordinate 2
	!arg5= y-Koordinate 2
	!arg6= z-Koordinate 3

/tspec,15

csys

*if,arg1,ne,arg4,then
	/AN3D,ANUM,0,105,arg1+5/10*(arg4-arg1),arg5,arg6
	/an3d,ARR2,0.5,arg1+4/10*(arg4-arg1),arg5,arg6,arg1,arg2,arg3
	/an3d,ARR2,0.5,arg1+6/10*(arg4-arg1),arg5,arg6,arg4,arg5,arg6
	/an3d,TEXT,arg1+5/10*(arg4-arg1),arg5,arg6,%abs(nint((arg4-arg1)*100)/10)%
*endif

*if,arg2,ne,arg5,then
	/AN3D,ANUM,0,105,arg4,arg2+5/10*(arg5-arg2),arg6
	/an3d,ARR2,0.5,arg4,arg2+4/10*(arg5-arg2),arg6,arg1,arg2,arg3
	/an3d,ARR2,0.5,arg4,arg2+6/10*(arg5-arg2),arg6,arg4,arg5,arg6
	/an3d,TEXT,arg4,arg2+5/10*(arg5-arg2),arg6,%abs(nint((arg5-arg2)*100)/10)%
*endif

*if,arg3,ne,arg6,then
	/AN3D,ANUM,0,105,arg4,arg5,arg3+5/10*(arg6-arg3)
	/an3d,ARR2,0.5,arg4,arg5,arg3+4/10*(arg6-arg3),arg1,arg2,arg3
	/an3d,ARR2,0.5,arg4,arg5,arg3+6/10*(arg6-arg3),arg4,arg5,arg6
	/an3d,TEXT,arg4,arg5,arg3+5/10*(arg6-arg3),%abs(nint((arg6-arg3)*100)/10)%
*endif

/tspec,15
!ende _______________________________________name____________________________________
/eof
cdir
!anfang _______________________________________cdir____________________________________
	!arg1 should be string
	/cwd,D:/%arg1%/ANSYS
!ende _______________________________________name____________________________________
/eof
plotMat
!anfang _______________________________________plotMat____________________________________
!nur in Post1 !
*get,rou_,active,,rout
*if,rou_,eq,31,then

	/nopr
	/plopts,info,on
	tsize_=0.8
	/tspec,15,tsize_,1,0,0
	/anno,tmod,1
	/anum,1

	cm,ee_,elem
	cm,nn_,node

	!deutsch / englisch
	*if,englisch_,lt,0.001,then
		englisch_=0
	*endif

		!Elementdicken
	*get,r1_,mat,,num,max
	r1_=500
	*set,vc3_
	*dim,vc3_,,r1_

	*do,i,1,r1_
		vc3_(i)=999999
		cmsel,s,ee_
		esel,r,mat,,i
		*get,e1_,elem,,count
		*if,e1_,gt,0,then
			vc3_(i)=i
		*endif
	*enddo

	!verschiedene Elementdicken suchen
	*set,vc2_
	*dim,vc2_,,50
	*do,i,1,50
		vc2_(i)=999999
	*enddo

	nv=0
	*do,i,1,r1_
		*if,vc3_(i),lt,999999,then
			*if,nv,eq,0,then
				nv=nv+1
				vc2_(nv)=vc3_(i)
			*endif
			nvn=0
			*do,j,1,nv
				*if,vc3_(i),eq,vc2_(j),then
					nvn=1
				*endif
			*enddo
			*if,nvn,eq,0,then
				nv=nv+1
				vc2_(nv)=vc3_(i)
			*endif
		*endif
	*enddo

	!Elementdicken sortieren
	*do,i,1,nv-1
		*do,j,i+1,nv
			*if,vc2_(i),gt,vc2_(j),then
				ii=vc2_(i)
				vc2_(i)=vc2_(j)
				vc2_(j)=ii
			*endif
		*enddo
	*enddo

	cmsel,s,ee_
	*get,emin_,elem,,num,min
	*get,emax_,elem,,num,max
	*get,eanz_,elem,,count

	*set,vec_
	*dim,vec_,,emax_

	etab,ddd,smisc,1

	ii=emin_
	*do,i,1,eanz_
		vec_(ii)=0
		*get,rc1_,elem,ii,attr,mat
		vec_(ii)=rc1_
		*get,ii,elem,ii,nxth
	*enddo

	*vput,vec_(1),elem,1,etab,ddd

	*if,nv,eq,0,then
		/cval,1,
	*elseif,nv,eq,1
		/cval,1,vc2_(1)
	*elseif,nv,eq,2
		/cval,1,vc2_(1),vc2_(2)
	*elseif,nv,eq,3
		/cval,1,vc2_(1),vc2_(2),vc2_(3)
	*elseif,nv,eq,4
		/cval,1,vc2_(1),vc2_(2),vc2_(3),vc2_(4)
	*elseif,nv,eq,5
		/cval,1,vc2_(1),vc2_(2),vc2_(3),vc2_(4),vc2_(5)
	*elseif,nv,eq,6
		/cval,1,vc2_(1),vc2_(2),vc2_(3),vc2_(4),vc2_(5),vc2_(6)
	*elseif,nv,eq,7
		/cval,1,vc2_(1),vc2_(2),vc2_(3),vc2_(4),vc2_(5),vc2_(6),vc2_(7)
	*else
		/cval,1,vc2_(1),vc2_(2),vc2_(3),vc2_(4),vc2_(5),vc2_(6),vc2_(7),vc2_(nv)
	*endif

	/anno,dele
	/tlabel, +1.040,-0.98,Material Number

	/anno,refr
	pletab,ddd
	/anno,dele
	/cval
	/go

	*set,vec_
	*set,vc2_
*endif
!ende _______________________________________name____________________________________
/eof
solFy
!anfang _______________________________________solFy____________________________________
!nur in Post1 !
/nopr
*get,rou_,active,,rout
*if,rou_,eq,31,then

	/nopr
	/plopts,info,on
	tsize_=0.8
	/tspec,15,tsize_,1,0,0
	/anno,tmod,1
	/anum,1
	
	cm,ee_,elem
	cm,nn_,node
	*use,solids
	*use,shells,1
	cmsel,r,ee_
	nsle
	cmsel,r,nn_
	cm,ee_,elem
	cm,nn_,node

	!deutsch / englisch
	*if,englisch_,lt,0.001,then
		englisch_=0
	*endif

	!Elementdicken
	!*get,r1_,mat,,num,max
	r1_=200
	*set,vc3_
	*dim,vc3_,,r1_

	*do,i,1,r1_
		vc3_(i)=999999
		cmsel,s,ee_
		esel,r,mat,,i
		*get,e1_,elem,,count
		*if,e1_,gt,0,then
			vc3_(i)=i
		*endif
	*enddo

	!verschiedene Elementdicken suchen
	*set,vc2_
	*dim,vc2_,,50

	nv=0		!counter
	*do,i,1,r1_
		*if,vc3_(i),lt,999999,then

			*if,nv,eq,0,then
				nv=nv+1
				vc2_(nv)=vc3_(i)
			*endif

			toAdd=1

			!check if already exists
			*do,j,1,nv
				*if,vc3_(i),eq,vc2_(j),then
					toAdd=0
					*exit
				*endif
			*enddo
			*if,toAdd,eq,1,then
				nv=nv+1
				vc2_(nv)=vc3_(i)
			*endif

		*endif
	*enddo

	!anfang Get element table and Replace it by Fy Vector
		cmsel,s,ee_
		*get,emin_,elem,,num,min
		*get,emax_,elem,,num,max
		*get,eanz_,elem,,count

		*set,vec_
		*dim,vec_,,emax_

		ii=emin_
		*do,i,1,eanz_
			vec_(ii)=0
			*get,rc1_,elem,ii,attr,mat
			rc2_=rc1_
			*get,rc1_,biso,rc2_,temp,0,const,1,
			vec_(ii)=rc1_
			*get,ii,elem,ii,nxth
		*enddo

		etable,ddd,smisc,1
		*vput,vec_(1),elem,1,etab,ddd
	!ende

	!Replace material number by Fy and Sort
	*do,iii,1,nv
		*get,vc2_(iii),biso,vc2_(iii),temp,0,const,1,
	*enddo
	arSort,'vc2_','nv'

	*if,nv,eq,0,then
		/cval,1,
	*elseif,nv,eq,1
		/cval,1,vc2_(1)
	*elseif,nv,eq,2
		/cval,1,vc2_(1),vc2_(2)
	*elseif,nv,eq,3
		/cval,1,vc2_(1),vc2_(2),vc2_(3)
	*elseif,nv,eq,4
		/cval,1,vc2_(1),vc2_(2),vc2_(3),vc2_(4)
	*elseif,nv,eq,5
		/cval,1,vc2_(1),vc2_(2),vc2_(3),vc2_(4),vc2_(5)
	*elseif,nv,eq,6
		/cval,1,vc2_(1),vc2_(2),vc2_(3),vc2_(4),vc2_(5),vc2_(6)
	*elseif,nv,eq,7
		/cval,1,vc2_(1),vc2_(2),vc2_(3),vc2_(4),vc2_(5),vc2_(6),vc2_(7)
	*else
		/cval,1,vc2_(1),vc2_(2),vc2_(3),vc2_(4),vc2_(5),vc2_(6),vc2_(7),vc2_(nv)
	*endif

	/anno,dele
	/tlabel, +1.040,-0.98,Yield Stresses (kN/cm2)
	/angle
	/auto

	/anno,refr
	pletab,ddd
	/anno,dele
	/cval
	/go

	*set,vec_
	*set,vc2_
*else
	/com, <<< Only works in Post1 >>> 
*endif
/gopr
!ende _______________________________________name____________________________________
/eof
matPlot
!anfang _______________________________________matPlot____________________________________
!nur in Post1 !
*get,rou_,active,,rout
*if,rou_,eq,31,then

	/nopr
	/plopts,info,on
	tsize_=0.8
	/tspec,15,tsize_,1,0,0
	/anno,tmod,1
	/anum,1

	cm,ee_,elem
	cm,nn_,node

	!deutsch / englisch
	*if,englisch_,lt,0.001,then
		englisch_=0
	*endif

	r1_=50
	*set,vc3_
	*dim,vc3_,,r1_

	*do,i,1,r1_
		vc3_(i)=0
	*enddo

	*get,elemNum,elem,,count
	*get,elemMin,elem,,num,min
	matCount=0
	*do,i,1,elemNum
		*get,matElem_,elem,elemMin,attr,mat
		incl=0
		*if,matCount,ge,1,then
			*do,j,1,matCount
				*if,matElem_,eq,vc3_(j),then
					incl=1
				*endif
			*enddo
		*endif
		*if,incl,eq,0,then
			matCount=matCount+1
			vc3_(matCount)=matElem_
		*endif
		*get,elemMin,elem,elemMin,nxth
	*enddo

	!verschiedene Elementdicken suchen
	*set,vc2_
	*dim,vc2_,,50
	*do,i,1,50
		vc2_(i)=0
	*enddo

	nv=0
	*do,i,1,r1_
		*if,vc3_(i),gt,0,then
			*if,nv,eq,0,then
				nv=nv+1
				vc2_(nv)=vc3_(i)
			*endif
			nvn=0
			*do,j,1,nv
				*if,vc3_(i),eq,vc2_(j),then
					nvn=1
				*endif
			*enddo
			*if,nvn,eq,0,then
				nv=nv+1
				vc2_(nv)=vc3_(i)
			*endif
		*endif
	*enddo

	!Elementdicken sortieren
	*do,i,1,nv-1
		*do,j,i+1,nv
			*if,vc2_(i),gt,vc2_(j),then
				ii=vc2_(i)
				vc2_(i)=vc2_(j)
				vc2_(j)=ii
			*endif
		*enddo
	*enddo

	cmsel,s,ee_
	*get,emin_,elem,,num,min
	*get,emax_,elem,,num,max
	*get,eanz_,elem,,count

	*set,vec_
	*dim,vec_,,emax_

	etable,ddd,smisc,1

	ii=emin_
	*do,i,1,eanz_
		vec_(ii)=0
		*get,rc1_,elem,ii,attr,mat
		vec_(ii)=rc1_
		*get,ii,elem,ii,nxth
	*enddo

	*vput,vec_(1),elem,1,etab,ddd

	*if,nv,eq,0,then
		/cval,1,
	*elseif,nv,eq,1
		/cval,1,vc2_(1)
	*elseif,nv,eq,2
		/cval,1,vc2_(1),vc2_(2)
	*elseif,nv,eq,3
		/cval,1,vc2_(1),vc2_(2),vc2_(3)
	*elseif,nv,eq,4
		/cval,1,vc2_(1),vc2_(2),vc2_(3),vc2_(4)
	*elseif,nv,eq,5
		/cval,1,vc2_(1),vc2_(2),vc2_(3),vc2_(4),vc2_(5)
	*elseif,nv,eq,6
		/cval,1,vc2_(1),vc2_(2),vc2_(3),vc2_(4),vc2_(5),vc2_(6)
	*elseif,nv,eq,7
		/cval,1,vc2_(1),vc2_(2),vc2_(3),vc2_(4),vc2_(5),vc2_(6),vc2_(7)
	*else
		/cval,1,vc2_(1),vc2_(2),vc2_(3),vc2_(4),vc2_(5),vc2_(6),vc2_(7),vc2_(nv)
	*endif

	/anno,dele
	/tlabel, +1.040,-0.98,Material Number

	/anno,refr
	pletab,ddd
	/anno,dele
	/cval
	/go

	*set,vec_
	*set,vc2_
*endif
!ende _______________________________________name____________________________________
/eof
plotFy
!anfang _______________________________________plotFy____________________________________
!nur in Post1 !Plots for Volume?
*get,rou_,active,,rout
*if,rou_,eq,31,then

	/nopr
	/plopts,info,on
	tsize_=0.8
	/tspec,15,tsize_,1,0,0
	/anno,tmod,1
	/anum,1

	cm,ee_1,elem
	cm,nn_1,node

	esel,u,ename,,170
	esel,u,ename,,174,175
	esel,u,ename,,154
	cm,ee_,elem
	cm,nn_,node

	!deutsch / englisch
	*if,englisch_,lt,0.001,then
		englisch_=0
	*endif

	r1_=50
	*set,vc3_
	*dim,vc3_,,r1_

	*do,i,1,r1_
		vc3_(i)=0
	*enddo

	*get,elemNum,elem,,count
	*get,elemMin,elem,,num,min
	matCount=0
	*do,i,1,elemNum
		*if,matCount,lt,r1_,then
			*get,matElem_,elem,elemMin,attr,mat
			*get,fy_,biso,matElem_,temp,0,const,1
			incl=0
			*if,matCount,ge,1,then
				*do,j,1,matCount
					*if,fy_,eq,vc3_(j),then
						incl=1
					*endif
				*enddo
			*endif
			!*stat,incl
			*if,incl,eq,0,then
				matCount=matCount+1
				!*stat,matCount
				*get,fy_,biso,matElem_,temp,0,const,1
				vc3_(matCount)=fy_
			*endif
			*get,elemMin,elem,elemMin,nxth
		*endif
	*enddo

	!verschiedene Elementdicken suchen
	*set,vc2_
	*dim,vc2_,,r1_
	*do,i,1,r1_
		vc2_(i)=0
	*enddo

	nv=0
	*do,i,1,r1_
		*if,vc3_(i),gt,0,then
			*if,nv,eq,0,then
				nv=nv+1
				vc2_(nv)=vc3_(i)
			*endif
			nvn=0
			*do,j,1,nv
				*if,vc3_(i),eq,vc2_(j),then
					nvn=1
				*endif
			*enddo
			*if,nvn,eq,0,then
				nv=nv+1
				vc2_(nv)=vc3_(i)
			*endif
		*endif
	*enddo

	!Elementdicken sortieren
	*do,i,1,nv-1
		*do,j,i+1,nv
			*if,vc2_(i),gt,vc2_(j),then
				ii=vc2_(i)
				vc2_(i)=vc2_(j)
				vc2_(j)=ii
			*endif
		*enddo
	*enddo

	cmsel,s,ee_
	*get,emin_,elem,,num,min
	*get,emax_,elem,,num,max
	*get,eanz_,elem,,count

	*set,vec_
	*dim,vec_,,emax_

	etable,ddd,smisc,1

	ii=emin_
	*do,i,1,eanz_
		vec_(ii)=0
		*get,rc1_,elem,ii,attr,mat
		*get,rc1_,biso,rc1_,temp,0,const,1
		vec_(ii)=rc1_
		*get,ii,elem,ii,nxth
	*enddo

	*vput,vec_(1),elem,1,etab,ddd

	*if,nv,eq,0,then
		/cval,1,
	*elseif,nv,eq,1
		/cval,1,vc2_(1)
	*elseif,nv,eq,2
		/cval,1,vc2_(1),vc2_(2)
	*elseif,nv,eq,3
		/cval,1,vc2_(1),vc2_(2),vc2_(3)
	*elseif,nv,eq,4
		/cval,1,vc2_(1),vc2_(2),vc2_(3),vc2_(4)
	*elseif,nv,eq,5
		/cval,1,vc2_(1),vc2_(2),vc2_(3),vc2_(4),vc2_(5)
	*elseif,nv,eq,6
		/cval,1,vc2_(1),vc2_(2),vc2_(3),vc2_(4),vc2_(5),vc2_(6)
	*elseif,nv,eq,7
		/cval,1,vc2_(1),vc2_(2),vc2_(3),vc2_(4),vc2_(5),vc2_(6),vc2_(7)
	*else
		/cval,1,vc2_(1),vc2_(2),vc2_(3),vc2_(4),vc2_(5),vc2_(6),vc2_(7),vc2_(nv)
	*endif

	/anno,dele
	/tlabel, +1.040,-0.98,Material Number

	/anno,refr
	cmsel,s,ee_1
	cmsel,s,nn_1
	pletab,ddd
	/anno,dele
	/cval
	/go

	*set,vec_
	*set,vc2_
*endif
!ende _______________________________________name____________________________________
/eof
pl7sm
!anfang _______________________________________pl7sm____________________________________
!ADPL-Macro :	Ergebnisdarstellung mit Beschriftung (Annotation)

!18.8.03 / 17.10.03 / 13.4.04 / 26.7.05 / 10.8.06 ge
!15.09.10 wa radialverfornung rsys,5

!arg1 : Darstellung von
!
!		= eplo : eplo
!                      = nplo : nplo
!                      = gplo : gplo
!                      = lplo : lplo
!                      = aplo : aplo
!
!                      = u    : pldi
!                      = usum : plns,u,sum
!                      = ux   : plns,u,x
!                      = uy   : plns,u,y
!                      = uz   : plns,u,z
!                      = ur   : plns,u,x , rsys,1
!                      = ut   : plns,u,y , rsys,1
!                      = ur5   : plns,u,y , rsys,5
!
!                      = sige : plns,sige
!                      = sigs : plns,sige (2 Plots, ohne/mit Skalierung)
!                      = sx   : plns,sx
!                      = sy   : plns,sy
!                      = sz   : plns,sz
!                      = sr   : plns,sx  , rsys,1
!                      = st   : plns,sy  , rsys,1
!                      = sxy  : plns,sxy
!                      = syz  : plns,syz
!                      = sxz  : plns,sxz
!                      = s1   : plns,s,1
!                      = s2   : plns,s,2
!                      = s3   : plns,s,3
!
!                      = eppl : plns,eppl,eqv
!                      = epps : plns,eppl,eqv (2 Plots, ohne/mit Skalierung)
!
!                      = sipl : plns,sige +
!                               plns,eppl,eqv (2 Plots)
!                      = sips : plns,sige +
!                             : plns,eppl,eqv (4 Plots, ohne/mit Skalierung)
!
!                      = fw   : Laengskraefte
!                      = fwm  : Schraubenlaengskraefte
!                      = fwms :    "      (2 Plots, ohne/mit Skalierung)
!                      = fwq  : Schraubenquerkraefte
!                      = fwc  : Kontaktkraefte
!                      = fwr  : Reibungskraefte
!                      = fwel : elastische Dehnungen LINK8
!                      = fwpl : plastische Dehnungen LINK8
!                      = fwx  : ohne Beschriftung
!                      = fwn  : Schraubennormalkraefte beam188
!                      = fwv  : Schraubenquerkraefte beam188
!
!                      = pcp  : Kontaktdruck  (Contac173)
!                      = pcs  : Kontaktstatus (Contac173)
!                      = pcf  : Kontaktfriction (Contac173)
!                      = pcd  : Kontaktslide (Contac173)
!                      = pcg  : Kontaktgap (Contac173)
!                      = pce  : Kontaktpenetration (Contac173)
!
!                      = pcps : Kontaktdruck  (2 Plots, ohne/mit Skalierung)
!
!arg2 : darstellungsspezifische Angaben :
!
!  fuer s...           = 1    : Spannung-top   (mit /gra,full)
!                      = 2    : Spannung-mid   (mit /gra,full)
!                      = 3    : Spannung-bot   (mit /gra,full)
!                      ohne   :                     /gra,powe
!
!  fuer u.             = 1    : mit unverformten System
!       pldi
!
!  fuer sigs, sips     Skalierungswert (i.a. Fliessgrenze)
!
!  fuer f...           = Skalierungsfaktor
!
!arg3 : darstellungsspezifische Angaben :
!
!  fuer fw...          = 1     : Summe mit angeben
!  fuer eppl           = 1     : auch zeigen, wenn keine plastischen Dehnungen vorhanden sind
!
!subtitles 1 - 4        werden als Annotation uebernommen
!                      ausser bei eplo, nplo werden stit3, stit4 benutzt
!
!englisch_ :            Variable (aussen gesetzt) = 1 : englische Texte
!
!einheit_  :            Variable (aussen gesetzt) = 1 : mm , N/mm2
!                                                  2 : m  , MN/m2
!                                                  3 : m  , N/m2
!
!

!arg4 : 1 if requested JPG, 9 if requested TIFF
!Customized 2014.12.11

/nopr
/plo,info,on
tsize_=0.8
/tspec,15,tsize_,1,0,0
/anno,tmod,1
/anum,1

!Subtitles uebernehmen
c01_='                        '
c02_='                        '
c03_='                        '
c04_='                        '

c1_='        '
*get,c1_,active,,title,1,start,1
*if,c1_,ne,'        ',then
	c01_=c1_
	*get,c1_,active,,title,1,start,9
	c01_=strfill(c01_,c1_,9)
	*get,c1_,active,,title,1,start,17
	c01_=strfill(c01_,c1_,17)
	*get,c1_,active,,title,1,start,25
	c01_=strfill(c01_,c1_,25)
	/tlab, +1.040,-0.745,%c01_%
*endif

c1_='        '
*get,c1_,active,,title,2,start,1
*if,c1_,ne,'        ',then
	c02_=c1_
	*get,c1_,active,,title,2,start,9
	c02_=strfill(c02_,c1_,9)
	*get,c1_,active,,title,2,start,17
	c02_=strfill(c02_,c1_,17)
	*get,c1_,active,,title,2,start,25
	c02_=strfill(c02_,c1_,25)
	/tlab, +1.040,-0.790,%c02_%
*endif

c1_='        '
*get,c1_,active,,title,3,start,1
*if,c1_,ne,'        ',then
	c03_=c1_
	*get,c1_,active,,title,3,start,9
	c03_=strfill(c03_,c1_,9)
	*get,c1_,active,,title,3,start,17
	c03_=strfill(c03_,c1_,17)
	*get,c1_,active,,title,3,start,25
	c03_=strfill(c03_,c1_,25)
	/tlab, +1.040,-0.835,%c03_%
*endif

c1_='        '
*get,c1_,active,,title,4,start,1
*if,c1_,ne,'        ',then
	c04_=c1_
	*get,c1_,active,,title,4,start,9
	c04_=strfill(c04_,c1_,9)
	*get,c1_,active,,title,4,start,17
	c04_=strfill(c04_,c1_,17)
	*get,c1_,active,,title,4,start,25
	c04_=strfill(c04_,c1_,25)
	/tlab, +1.040,-0.880,%c04_%
*endif

!deutsch / englisch
*if,englisch_,lt,0.001,then
	englisch_=0
*endif

*if,englisch_,eq,1,then
	gesamt_='Total'
	versch_=' displacements'
	spann_ =' stresses'
	top_   ='top side'
	mid_   ='midplane'
	bot_   ='bottom side'
	sum_   ='sum'
*else
	gesamt_='Gesamt'
	versch_='-Verschiebungen'
	spann_ ='-Spannungen'
	top_   ='Oberseite'
	mid_   ='Membran'
	bot_   ='Unterseite'
	sum_   ='Summe'
*endif

!Einheiten

*if,einheit_,lt,0.001,then
	einheit_=0
*endif

*if,einheit_,eq,1,then
	cm_='(mm)'
	kN_='(N)'
	kNcm2_='(N/mm2)'
*elseif,einheit_,eq,2,then
	cm_='(m)'
	kN_='(MN)'
	kNcm2_='(MN/m2)'
*elseif,einheit_,eq,3,then
	cm_='(m)'
	kN_='(N)'
	kNcm2_='(N/m2)'
*else
	cm_='(cm)'
	kN_='(kN)'
	kNcm2_='(kN/cm2)'
*endif

!Darstellung entsprechend arg1

*if,arg1,eq,'eplo',then
	eplo
*elseif,arg1,eq,'nplo',then
	nplo
*elseif,arg1,eq,'gplo',then
	gplo
*elseif,arg1,eq,'lplo',then
	lplo
*elseif,arg1,eq,'aplo',then
	aplo
*elseif,arg1,eq,'usum',then
	/tlab, +1.040,-0.935,%Gesamt_%%versch_%
	/tlab, +1.040,-0.980,%cm_%
	plns,u,sum,arg2
*elseif,arg1,eq,'ux',then
	/tlab, +1.040,-0.935,x%versch_%
	/tlab, +1.040,-0.980,%cm_%
	plns,ux,,arg2
*elseif,arg1,eq,'uy',then
	/tlab, +1.040,-0.935,y%versch_%
	/tlab, +1.040,-0.980,%cm_%
	plns,uy,,arg2
*elseif,arg1,eq,'uz',then
	/tlab, +1.040,-0.935,z%versch_%
	/tlab, +1.040,-0.980,%cm_%
	plns,uz,,arg2
*elseif,arg1,eq,'ur',then
	*if,englisch_,eq,0,then
		/tlab, +1.040,-0.935,Radial-Verschiebungen
	*elseif,englisch_,eq,1,then
		/tlab, +1.040,-0.935,radial displacements
	*endif
	/tlab, +1.040,-0.980,%cm_%
	rsys,1
	plns,ux,,arg2
	rsys
*elseif,arg1,eq,'ur5',then
	*if,englisch_,eq,0,then
		/tlab, +1.040,-0.935,Radial-Verschiebungen
	*elseif,englisch_,eq,1,then
	/tlab, +1.040,-0.935,radial displacements
	*endif
	/tlab, +1.040,-0.980,%cm_%
	rsys,5
	plns,ux,,arg2
	rsys
*elseif,arg1,eq,'ut',then
	*if,englisch_,eq,0,then
		/tlab, +1.040,-0.935,Tangential-Verschiebungen
	*elseif,englisch_,eq,1,then
		/tlab, +1.040,-0.935,tangential displacements
	*endif
	/tlab, +1.040,-0.980,%cm_%
	rsys,1
	plns,uy,,arg2
	rsys
*elseif,arg1,eq,'u',then
	*if,englisch_,eq,0,then
		/tlab, +1.040,-0.980,Verformungen
	*elseif,englisch_,eq,1,then
		/tlab, +1.040,-0.980,deformations
	*endif
	pldi,arg2
*elseif,arg1,eq,'sige',then
	*if,englisch_,eq,0,then
		/tlab, +1.040,-0.935,Vergleichsspannungen
	*elseif,englisch_,eq,1,then
		/tlab, +1.040,-0.935,von Mises stresses
	*endif
	*if,arg2,eq,1,then
		/tlab, +1.040,-0.980,%top_% %kNcm2_%
		/gra,full
		top
	*elseif,arg2,eq,2,then
		/tlab, +1.040,-0.980,%mid_% %kNcm2_%
		mid
	*elseif,arg2,eq,3,then
		/tlab, +1.040,-0.980,%bot_% %kNcm2_%
		/gra,full
		bot
	*else
		/gra,powe
		top
		/tlab, +1.040,-0.980,%kNcm2_%
	*endif
	plns,sige
	top
*elseif,arg1,eq,'sigs',then
	*if,englisch_,eq,0,then
		/tlab, +1.040,-0.935,Vergleichsspannungen
	*elseif,englisch_,eq,1,then
		/tlab, +1.040,-0.935,von Mises stresses
	*endif
	/gra,powe
	top
	/tlab, +1.040,-0.980,%kNcm2_%
	/cval
	jplot
		plns,sige
		*get,max_,plns,,max
	jplot,arg4
	*if,arg2,gt,0.01,then
		*if,max_,gt,arg2,then
			v1_=nint(1*arg2/7*100)/100
			v2_=nint(2*arg2/7*100)/100
			v3_=nint(3*arg2/7*100)/100
			v4_=nint(4*arg2/7*100)/100
			v5_=nint(5*arg2/7*100)/100
			v6_=nint(6*arg2/7*100)/100
			/cval,,v1_,v2_,v3_,v4_,v5_,v6_,arg2,max_
			plns,sige
			/cval
		*endif
	*endif
*elseif,arg1,eq,'sx',then
	/tlab, +1.040,-0.935,x%spann_%
	*if,arg2,eq,1,then
		/tlab, +1.040,-0.980,%top_% %kNcm2_%
		/gra,full
		top
	*elseif,arg2,eq,2,then
		/tlab, +1.040,-0.980,%mid_% %kNcm2_%
		mid
	*elseif,arg2,eq,3,then
		/tlab, +1.040,-0.980,%bot_% %kNcm2_%
		/gra,full
		bot
	*else
		/gra,powe
		top
		/tlab, +1.040,-0.980,%kNcm2_%
	*endif
	plns,sx
	top
*elseif,arg1,eq,'sy',then
	/tlab, +1.040,-0.935,y%spann_%
	*if,arg2,eq,1,then
		/tlab, +1.040,-0.980,%top_% %kNcm2_%
		/gra,full
		top
	*elseif,arg2,eq,2,then
		/tlab, +1.040,-0.980,%mid_% %kNcm2_%
		mid
	*elseif,arg2,eq,3,then
		/tlab, +1.040,-0.980,%bot_% %kNcm2_%
		/gra,full
		bot
	*else
		/gra,powe
		top
		/tlab, +1.040,-0.980,%kNcm2_%
	*endif
	plns,sy
	top
*elseif,arg1,eq,'sr',then
	*if,englisch_,eq,0,then
		/tlab, +1.040,-0.935,Radial%spann_%
	*elseif,englisch_,eq,1,then
		/tlab, +1.040,-0.935,radial stresses
	*endif
	*if,arg2,eq,1,then
		/tlab, +1.040,-0.980,%top_% %kNcm2_%
		/gra,full
		top
	*elseif,arg2,eq,2,then
		/tlab, +1.040,-0.980,%mid_% %kNcm2_%
		mid
	*elseif,arg2,eq,3,then
		/tlab, +1.040,-0.980,%bot_% %kNcm2_%
		/gra,full
		bot
	*else
		/gra,powe
		top
		/tlab, +1.040,-0.980,%kNcm2_%
	*endif
	rsys,1
	plns,sx
	rsys
	top
*elseif,arg1,eq,'st',then
	*if,englisch_,eq,0,then
		/tlab, +1.040,-0.935,Umfangs%spann_%
	*elseif,englisch_,eq,1,then
		/tlab, +1.040,-0.935,circumferential stresses
	*endif
	*if,arg2,eq,1,then
		/tlab, +1.040,-0.980,%top_% %kNcm2_%
		/gra,full
		top
	*elseif,arg2,eq,2,then
		/tlab, +1.040,-0.980,%mid_% %kNcm2_%
		mid
	*elseif,arg2,eq,3,then
		/tlab, +1.040,-0.980,%bot_% %kNcm2_%
		/gra,full
		bot
	*else
		/gra,powe
		top
		/tlab, +1.040,-0.980,%kNcm2_%
	*endif
	rsys,1
	plns,sy
	rsys
	top
*elseif,arg1,eq,'sz',then
	/tlab, +1.040,-0.935,z%spann_%
	*if,arg2,eq,1,then
		/tlab, +1.040,-0.980,%top_% %kNcm2_%
		/gra,full
		top
	*elseif,arg2,eq,2,then
		/tlab, +1.040,-0.980,%mid_% %kNcm2_%
		mid
	*elseif,arg2,eq,3,then
		/tlab, +1.040,-0.980,%bot_% %kNcm2_%
		/gra,full
		bot
	*else
		/gra,powe
		top
		/tlab, +1.040,-0.980,%kNcm2_%
	*endif
	plns,sz
	top
*elseif,arg1,eq,'sxy',then
	/tlab, +1.040,-0.935,xy%spann_%
	*if,arg2,eq,1,then
		/tlab, +1.040,-0.980,%top_% %kNcm2_%
		/gra,full
		top
	*elseif,arg2,eq,2,then
		/tlab, +1.040,-0.980,%mid_% %kNcm2_%
		mid
	*elseif,arg2,eq,3,then
		/tlab, +1.040,-0.980,%bot_% %kNcm2_%
		/gra,full
		bot
	*else
		/gra,powe
		top
		/tlab, +1.040,-0.980,%kNcm2_%
	*endif
	plns,sxy
	top
*elseif,arg1,eq,'syz',then
	/tlab, +1.040,-0.935,yz%spann_%
	*if,arg2,eq,1,then
		/tlab, +1.040,-0.980,%top_% %kNcm2_%
		/gra,full
		top
	*elseif,arg2,eq,2,then
		/tlab, +1.040,-0.980,%mid_% %kNcm2_%
		mid
	*elseif,arg2,eq,3,then
		/tlab, +1.040,-0.980,%bot_% %kNcm2_%
		/gra,full
		bot
	*else
		/gra,powe
		top
		/tlab, +1.040,-0.980,%kNcm2_%
	*endif
	plns,syz
	top
*elseif,arg1,eq,'sxz',then
	/tlab, +1.040,-0.935,xz%spann_%
	*if,arg2,eq,1,then
		/tlab, +1.040,-0.980,%top_% %kNcm2_%
		/gra,full
		top
	*elseif,arg2,eq,2,then
		/tlab, +1.040,-0.980,%mid_% %kNcm2_%
		mid
	*elseif,arg2,eq,3,then
		/tlab, +1.040,-0.980,%bot_% %kNcm2_%
		/gra,full
		bot
	*else
		/gra,powe
		top
		/tlab, +1.040,-0.980,%kNcm2_%
	*endif
	plns,sxz
	top
*elseif,arg1,eq,'s1',then
	*if,englisch_,eq,0,then
		!/tlab, +1.040,-0.935,Hauptzugspannung
		/tlab, +1.040,-0.935,max. Hauptspannung
	*elseif,englisch_,eq,1,then
		/tlab, +1.040,-0.935,main tension stress
	*endif
	*if,arg2,eq,1,then
		/tlab, +1.040,-0.980,%top_% %kNcm2_%
		/gra,full
		top
	*elseif,arg2,eq,2,then
		/tlab, +1.040,-0.980,%mid_% %kNcm2_%
		mid
	*elseif,arg2,eq,3,then
		/tlab, +1.040,-0.980,%bot_% %kNcm2_%
		/gra,full
		bot
	*else
		/gra,powe
		top
		/tlab, +1.040,-0.980,%kNcm2_%
	*endif
	plns,s,1
	top
*elseif,arg1,eq,'s2',then
	*if,englisch_,eq,0,then
		/tlab, +1.040,-0.935,2. Hauptspannung
	*elseif,englisch_,eq,1,then
		/tlab, +1.040,-0.935,2. main stress
	*endif
	*if,arg2,eq,1,then
		/tlab, +1.040,-0.980,%top_% %kNcm2_%
		/gra,full
		top
	*elseif,arg2,eq,2,then
		/tlab, +1.040,-0.980,%mid_% %kNcm2_%
		mid
	*elseif,arg2,eq,3,then
		/tlab, +1.040,-0.980,%bot_% %kNcm2_%
		/gra,full
		bot
	*else
		/gra,powe
		top
		/tlab, +1.040,-0.980,%kNcm2_%
	*endif
	plns,s,2
	top
*elseif,arg1,eq,'s3',then
	*if,englisch_,eq,0,then
		!/tlab, +1.040,-0.935,Hauptdruckspannung
		/tlab, +1.040,-0.935,min. Hauptspannung
	*elseif,englisch_,eq,1,then
		/tlab, +1.040,-0.935,main pressure stress
	*endif
	*if,arg2,eq,1,then
		/tlab, +1.040,-0.980,%top_% %kNcm2_%
		/gra,full
		top
	*elseif,arg2,eq,2,then
		/tlab, +1.040,-0.980,%mid_% %kNcm2_%
		mid
	*elseif,arg2,eq,3,then
		/tlab, +1.040,-0.980,%bot_% %kNcm2_%
		/gra,full
		bot
	*else
		/gra,powe
		top
		/tlab, +1.040,-0.980,%kNcm2_%
	*endif
	plns,s,3
	top
*elseif,arg1,eq,'eppl',then
	*if,englisch_,eq,0,then
		/tlab, +1.040,-0.935,plast. Vergleichsdehnungen
	*elseif,englisch_,eq,1,then
		/tlab, +1.040,-0.935,equiv. plastic strains
	*endif
	*if,arg2,eq,1,then
		/tlab, +1.040,-0.980,%top_% (-)
		/gra,full
		top
		nsort,eppl,eqv
		*get,max_,sort,,max
	*elseif,arg2,eq,2,then
		/tlab, +1.040,-0.980,%mid_% (-)
		/gra,full
		top
		nsort,eppl,eqv
		*get,maxt_,sort,,max
		bot
		nsort,eppl,eqv
		*get,maxb_,sort,,max
		max_=max(maxt_,maxb_)
		mid
		/gra,powe
	*elseif,arg2,eq,3,then
		/tlab, +1.040,-0.980,%bot_% (-)
		/gra,full
		bot
		nsort,eppl,eqv
		*get,max_,sort,,max
		*else
		/gra,full
		top
		nsort,eppl,eqv
		*get,maxt_,sort,,max
		bot
		nsort,eppl,eqv
		*get,maxb_,sort,,max
		max_=max(maxt_,maxb_)
		/gra,powe
		/tlab, +1.040,-0.980,(-)
	*endif
	/anno,refr
	*if,arg3,eq,1,then
	*else
		plns,eppl,eqv
		*if,max_,gt,1.e-10,then
			plns,eppl,eqv
		*endif
	*endif
*elseif,arg1,eq,'epps',then
	*if,englisch_,eq,0,then
		/tlab, +1.040,-0.935,plast. Vergleichsdehnungen
	*elseif,englisch_,eq,1,then
		/tlab, +1.040,-0.935,equiv. plastic strains
	*endif
	/tlab, +1.040,-0.980,(-)
	/gra,full
	*if,arg5,eq,1,then
		max_=1
	*else
		top
		nsort,eppl,eqv
		*get,maxt_,sort,,max
		bot
		nsort,eppl,eqv
		*get,maxb_,sort,,max
		max_=max(maxt_,maxb_)
		/gra,powe
	*endif
	/anno,refr
	*if,max_,gt,1.e-10,or,arg3,eq,1,then
		jplot
		plns,eppl,eqv
		*get,max_,plns,,max
		jplot,arg4
		*if,max_,gt,1.e-10,then
			v1_=0.0001*max_
			v2_=0.001*max_
			v3_=0.01*max_
			v4_=0.10*max_
			v5_=0.20*max_
			v6_=0.50*max_
			v7_=0.80*max_
			/cval,,v1_,v2_,v3_,v4_,v5_,v6_,v7_,max_
			plns,eppl,eqv
			/cval
		*endif
	*endif
*elseif,arg1,eq,'sipl',then
	*if,englisch_,eq,0,then
		/tlab, +1.040,-0.935,Vergleichsspannungen
	*elseif,englisch_,eq,1,then
		/tlab, +1.040,-0.935,von Mises stresses
	*endif
	*if,arg2,eq,1,then
		/tlab, +1.040,-0.980,%top_% %kNcm2_%
		/gra,full
		top
	*elseif,arg2,eq,2,then
		/tlab, +1.040,-0.980,%mid_% %kNcm2_%
		mid
	*elseif,arg2,eq,3,then
		/tlab, +1.040,-0.980,%bot_% %kNcm2_%
		/gra,full
		bot
	*else
		/gra,powe
		top
		/tlab, +1.040,-0.980,%kNcm2_%
	*endif

	plns,sige

	/anno,dele
	/tlab, +1.040,-0.745,%c01_%
	/tlab, +1.040,-0.790,%c02_%
	/tlab, +1.040,-0.835,%c03_%
	/tlab, +1.040,-0.880,%c04_%
	top
	*if,englisch_,eq,0,then
		/tlab, +1.040,-0.935,plast. Vergleichsdehnungen
	*elseif,englisch_,eq,1,then
		/tlab, +1.040,-0.935,equiv. plastic strains
	*endif
	*if,arg2,eq,1,then
		/tlab, +1.040,-0.980,%top_% (-)
		/gra,full
		top
		nsort,eppl,eqv
		*get,max_,sort,,max
	*elseif,arg2,eq,2,then
		/tlab, +1.040,-0.980,%mid_% (-)
		/gra,full
		top
		nsort,eppl,eqv
		*get,maxt_,sort,,max
		bot
		nsort,eppl,eqv
		*get,maxb_,sort,,max
		max_=max(maxt_,maxb_)
		mid
		/gra,powe
	*elseif,arg2,eq,3,then
		/tlab, +1.040,-0.980,%bot_% (-)
		/gra,full
		bot
		nsort,eppl,eqv
		*get,max_,sort,,max
	*else
		/gra,full
		top
		nsort,eppl,eqv
		*get,maxt_,sort,,max
		bot
		nsort,eppl,eqv
		*get,maxb_,sort,,max
		max_=max(maxt_,maxb_)
		/gra,powe
		/tlab, +1.040,-0.980,(-)
	*endif
	/anno,refr
	*if,max_,gt,1.e-10,then
		plns,eppl,eqv
	*endif
*elseif,arg1,eq,'sips',then
	*if,englisch_,eq,0,then
		/tlab, +1.040,-0.935,Vergleichsspannungen
	*elseif,englisch_,eq,1,then
		/tlab, +1.040,-0.935,von Mises stresses
	*endif
		/tlab, +1.040,-0.980,%kNcm2_%
		/gra,powe
		top
		/cval
		jplot
		plns,sige
		*get,max_,plns,,max
		jplot,arg4
	*if,arg2,gt,0.01,then
		*if,max_,gt,arg2,then
			v1_=nint(1*arg2/7*100)/100
			v2_=nint(2*arg2/7*100)/100
			v3_=nint(3*arg2/7*100)/100
			v4_=nint(4*arg2/7*100)/100
			v5_=nint(5*arg2/7*100)/100
			v6_=nint(6*arg2/7*100)/100
			/cval,,v1_,v2_,v3_,v4_,v5_,v6_,arg2,max_
		*endif
	*endif
			plns,sige

			/cval

	/anno,dele
	/tlab, +1.040,-0.745,%c01_%
	/tlab, +1.040,-0.790,%c02_%
	/tlab, +1.040,-0.835,%c03_%
	/tlab, +1.040,-0.880,%c04_%
	top
	*if,englisch_,eq,0,then
		/tlab, +1.040,-0.935,plast. Vergleichsdehnungen
	*elseif,englisch_,eq,1,then
		/tlab, +1.040,-0.935,equiv. plastic strains
	*endif
	/gra,full
	top
	nsort,eppl,eqv
	*get,maxt_,sort,,max
	bot
	nsort,eppl,eqv
	*get,maxb_,sort,,max
	max_=max(maxt_,maxb_)
	/gra,powe
	/tlab, +1.040,-0.980,(-)
	/anno,refr
		/cval
		jplot

		plns,eppl,eqv

		jplot,arg4
	*if,max_,gt,1.e-10,then
		*get,max_,plns,,max
		v1_=0.0001*max_
		v2_=0.001*max_
		v3_=0.01*max_
		v4_=0.10*max_
		v5_=0.20*max_
		v6_=0.50*max_
		v7_=0.80*max_
		/cval,,v1_,v2_,v3_,v4_,v5_,v6_,v7_,max_
	*endif
		plns,eppl,eqv
		/cval
*elseif,arg1,eq,'fw',then
	*if,englisch_,eq,0,then
		/tlab, +1.040,-0.935,Laengskraefte %kN_%
	*elseif,englisch_,eq,1,then
		/tlab, +1.040,-0.935,normal forces %kN_%
	*endif
	*if,arg3,ne,0,then
		etab,fxi,smisc,1
		ssum
		*get,f1,ssum,,item,fxi
		f1=abs(nint(f1*100)/100)
		/tlab, +1.040,-0.980,%sum_%: %f1% %kN_%
	*endif
	fw,arg2
*elseif,arg1,eq,'fwm',then
	*if,englisch_,eq,0,then
		/tlab, +1.040,-0.935,Schraubenzugkraefte %kN_%
	*elseif,englisch_,eq,1,then
		/tlab, +1.040,-0.935,bolt tension forces %kN_%
	*endif
	*if,arg3,ne,0,then
		etab,fxi,smisc,1
		ssum
		*get,f1,ssum,,item,fxi
		f1=abs(nint(f1*100)/100)
		/tlab, +1.040,-0.980,%sum_%: %f1% %kN_%
	*endif
	fw,arg2
*elseif,arg1,eq,'fwms',then
	*if,englisch_,eq,0,then
		/tlab, +1.040,-0.935,Schraubenzugkraefte %kN_%
	*elseif,englisch_,eq,1,then
		/tlab, +1.040,-0.935,bolt tension forces %kN_%
	*endif
	etab,fxi,smisc,1
	*if,arg3,ne,0,then
		ssum
		*get,f1,ssum,,item,fxi
		f1=abs(nint(f1*100)/100)
		/tlab, +1.040,-0.980,%sum_%: %f1% %kN_%
	*endif
	esort,etab,fxi
	*get,min_,sort,,min
	*get,max_,sort,,max
	*if,max_,gt,arg4,then
		v0=arg4-min_
		v1_=nint(min_+1*v0/7)
		v2_=nint(min_+2*v0/7)
		v3_=nint(min_+3*v0/7)
		v4_=nint(min_+4*v0/7)
		v5_=nint(min_+5*v0/7)
		v6_=nint(min_+6*v0/7)
		/cval,,v1_,v2_,v3_,v4_,v5_,arg4,max_*1.000001
	*endif
	plls,fxi,fxi,arg2
	/cval
*elseif,arg1,eq,'fwq',then
	*if,englisch_,eq,0,then
		/tlab, +1.040,-0.935,Schraubenquerkraefte %kN_%
	*elseif,englisch_,eq,1,then
		/tlab, +1.040,-0.935,bolt shear forces %kN_%
	*endif
	*if,arg3,ne,0,then
		etab,fyi,smisc,2
		etab,fzi,smisc,3
		smult,fyyi,fyi,fyi
		smult,fzzi,fzi,fzi
		sadd,yzii,fyyi,fzzi
		sexp,fyzi,yzii,,0.5
		ssum
		*get,f1,ssum,,item,fyzi
		f1=abs(nint(f1*100)/100)
		/tlab, +1.040,-0.980,%sum_%: %f1% %kN_%
	*endif
	qres,arg2
*elseif,arg1,eq,'fwc',then
	*if,englisch_,eq,0,then
		/tlab, +1.040,-0.935,Druckkontaktkraefte %kN_%
	*elseif,englisch_,eq,1,then
		/tlab, +1.040,-0.935,contact pressure forces %kN_%
	*endif
	*if,arg3,ne,0,then
		etab,fxi,smisc,1
		ssum
		*get,f1,ssum,,item,fxi
		f1=abs(nint(f1*100)/100)
		/tlab, +1.040,-0.980,%sum_%: %f1% %kN_%
	*endif
	fw,arg2
*elseif,arg1,eq,'fwr',then
	*if,englisch_,eq,0,then
		/tlab, +1.040,-0.935,Reibungskraefte %kN_%
	*elseif,englisch_,eq,1,then
		/tlab, +1.040,-0.935,friction forces %kN_%
	*endif
	*if,arg3,ne,0,then
		etab,fyi,smisc,2
		ssum
		*get,f1,ssum,,item,fyi
		f1=abs(nint(f1*100)/100)
		/tlab, +1.040,-0.980,%sum_%: %f1% %kN_%
	*endif
	fws,arg2
*elseif,arg1,eq,'fwel',then
	*if,englisch_,eq,0,then
		/tlab, +1.040,-0.935,elastische Dehnungen
	*elseif,englisch_,eq,1,then
		/tlab, +1.040,-0.935,elastic strains
	*endif
	etab,lepel,lepel,1
	plls,lepel,lepel,arg2
	*set,lepel
*elseif,arg1,eq,'fwpl',then
	*if,englisch_,eq,0,then
		/tlab, +1.040,-0.935,plastische Dehnungen
	*elseif,englisch_,eq,1,then
		/tlab, +1.040,-0.935,plastic strains
	*endif
	etab,leppl,leppl,1
	plls,leppl,leppl,arg2
	*set,leppl
*elseif,arg1,eq,'fwx',then
	*if,arg3,ne,0,then
		etab,fxi,smisc,1
		ssum
		*get,f1,ssum,,item,fxi
		f1=abs(nint(f1*100)/100)
		/tlab, +1.040,-0.980,%sum_%: %f1% %kN_%
	*endif
	fw,arg2
*elseif,arg1,eq,'fwn',then
	*if,englisch_,eq,0,then
		/tlab, +1.040,-0.935,Schraubenzugkraefte %kN_%
	*elseif,englisch_,eq,1,then
		/tlab, +1.040,-0.935,bolt tension forces %kN_%
	*endif
	*if,arg3,ne,0,then
		etab,fxi,smisc,1
		ssum
		*get,f1,ssum,,item,fxi
		f1=abs(nint(f1*100)/100)
		/tlab, +1.040,-0.980,%sum_%: %f1% %kN_%
	*endif
	fw,arg2
*elseif,arg1,eq,'fwv',then
	*if,englisch_,eq,0,then
		/tlab, +1.040,-0.935,Schraubenquerkraefte %kN_%
	*elseif,englisch_,eq,1,then
		/tlab, +1.040,-0.935,bolt shear forces %kN_%
	*endif
	*if,arg3,ne,0,then
		etab,fyi,smisc,5
		etab,fzi,smisc,6
		smult,fyyi,fyi,fyi
		smult,fzzi,fzi,fzi
		sadd,yzii,fyyi,fzzi
		sexp,fyzi,yzii,,0.5
		ssum
		*get,f1,ssum,,item,fyzi
		f1=abs(nint(f1*100)/100)
	/tlab, +1.040,-0.980,%sum_%: %f1% %kN_%
	*endif
	qres2,arg2
*elseif,arg1,eq,'pcp',then
	*if,englisch_,eq,0,then
		/tlab, +1.040,-0.935,Kontaktdruck %kNcm2_%
	*elseif,englisch_,eq,1,then
		/tlab, +1.040,-0.935,contact pressure %kNcm2_%
	*endif
	*if,arg3,eq,1,then
		fsum,,cont
		*get,f1_,fsum,,item,fx
		*get,f2_,fsum,,item,fy
		*get,f3_,fsum,,item,fz
		f1_=sqrt(f1_**2+f2_**2+f3_**2)
		f1_=abs(nint(f1_*100)/100)
		/tlab, +1.040,-0.980,%sum_%: %f1_% %kN_%
	*elseif,arg3,eq,2,then
		fsum,,cont
		*get,f1_,fsum,,item,fx
		*get,f2_,fsum,,item,fy
		*get,f3_,fsum,,item,fz
		f1_=abs(nint(f1_))
		f2_=abs(nint(f2_))
		f3_=abs(nint(f3_))
		/tlab, +1.040,-0.980,Fx=%f1_%,Fy=%f2_%,Fz=%f3_% %kN_%
	*elseif,arg3,eq,3,then
		fsum,,cont
		*get,f1_,fsum,,item,fx
		*get,f2_,fsum,,item,fy
		*get,f3_,fsum,,item,fz
		f1_=abs(nint(f1_*10)/10)
		f2_=abs(nint(f2_*10)/10)
		f3_=abs(nint(f3_*10)/10)
		/tlab, +1.040,-0.980,Fx=%f1_%,Fy=%f2_%,Fz=%f3_% %kN_%
	*endif
	plns,cont,pres
*elseif,arg1,eq,'pcs',then
	*if,englisch_,eq,0,then
		/tlab, +1.040,-0.935,Kontaktstatus (0,1=offen;
		/tlab, +1.040,-0.980, 2=gleiten; 3=haften)
	*elseif,englisch_,eq,1,then
		/tlab, +1.040,-0.935,contact status
		/tlab, +1.040,-0.980,(3=stick;2=slide;0,1=open)
	*endif
	/cval,1,1,2,3
	plns,cont,stat
	/con,1,9
*elseif,arg1,eq,'pcf',then
	*if,englisch_,eq,0,then
		/tlab, +1.040,-0.935,Kontaktreibung %kNcm2_%
	*elseif,englisch_,eq,1,then
		/tlab, +1.040,-0.935,contact friction %kNcm2_%
	*endif
	plns,cont,sfric
*elseif,arg1,eq,'pcd',then
	*if,englisch_,eq,0,then
		/tlab, +1.040,-0.935,Kontakt-Gleitung %cm_%
	*elseif,englisch_,eq,1,then
		/tlab, +1.040,-0.935,contact slide %cm_%
	*endif
	plns,cont,slide
*elseif,arg1,eq,'pcg',then
	*if,englisch_,eq,0,then
		/tlab, +1.040,-0.935,Kontakt-Spalt %cm_%
	*elseif,englisch_,eq,1,then
		/tlab, +1.040,-0.935,contact gap %cm_%
	*endif
	plns,cont,gap
*elseif,arg1,eq,'pce',then
	*if,englisch_,eq,0,then
		/tlab, +1.040,-0.935,Kontakt-Penetration
		/tlab, +1.040,-0.980,%cm_%
	*elseif,englisch_,eq,1,then
		/tlab, +1.040,-0.935,contact penetration
		/tlab, +1.040,-0.980,%cm_%
	*endif
	plns,cont,pene
*elseif,arg1,eq,'pcps',then
	*if,englisch_,eq,0,then
		/tlab, +1.040,-0.935,Kontaktdruck %kNcm2_%
	*elseif,englisch_,eq,1,then
		/tlab, +1.040,-0.935,contact pressure %kNcm2_%
	*endif
	*if,arg3,eq,1,then
		fsum,,cont
		*get,f1_,fsum,,item,fx
		*get,f2_,fsum,,item,fy
		*get,f3_,fsum,,item,fz
		f1_=sqrt(f1_**2+f2_**2+f3_**2)
		f1_=abs(nint(f1_*100)/100)
		/tlab, +1.040,-0.980,%sum_%: %f1_% %kN_%
	*elseif,arg3,eq,2,then
		fsum,,cont
		*get,f1_,fsum,,item,fx
		*get,f2_,fsum,,item,fy
		*get,f3_,fsum,,item,fz
		f1_=abs(nint(f1_))
		f2_=abs(nint(f2_))
		f3_=abs(nint(f3_))
		/tlab, +1.040,-0.980,Fx=%f1_%,Fy=%f2_%,Fz=%f3_% %kN_%
	*elseif,arg3,eq,3,then
		fsum,,cont
		*get,f1_,fsum,,item,fx
		*get,f2_,fsum,,item,fy
		*get,f3_,fsum,,item,fz
		f1_=abs(nint(f1_*10)/10)
		f2_=abs(nint(f2_*10)/10)
		f3_=abs(nint(f3_*10)/10)
		/tlab, +1.040,-0.980,Fx=%f1_%,Fy=%f2_%,Fz=%f3_% %kN_%
	*endif
	/cval
	jplot

	plns,cont,pres

	jplot,arg4
	*get,max_,plns,,max
	v1_=0.0001*max_
	v2_=0.001*max_
	v3_=0.01*max_
	v4_=0.10*max_
	v5_=0.20*max_
	v6_=0.50*max_
	v7_=0.80*max_
	/cval,,v1_,v2_,v3_,v4_,v5_,v6_,v7_,max_
	plns,cont,pres
	/cval
*endif

/anno,dele
/go
!ende _______________________________________name____________________________________
/eof
di78sm
!anfang _______________________________________di78sm____________________________________
!Macro zum Darstellen der Elementdicke!zeigt jeweils die Elemente mit derselben Dicke !darzustellende Elemente und Knoten sind bereits ausgewaehlt
!wie di71, aber uebernimmt stits !wie di73, aber sortiert die Blechstärken nach sectype !Komponentenname tbl_i
!21.01.10 kurz
!Elemente werden durchsichtig dargestellt	10.01.14 kurz !/type muss auf /type,,6 gestellt sein
!arg1 : = 0 : Bleche !        1 : Schweissnaht !englisch_ :            Variable (aussen gesetzt) = 1 : englische Texte   = 2 : französische Texte

/plo,info,on
tsize_=0.8
/tspec,15,tsize_,1,0,0
/anno,tmod,1
/anum,1

cm,di7_,elem
cm,di8_,node

!deutsch / englisch
*if,englisch_,lt,0.001,then
	englisch_=0
*endif

*if,englisch_,eq,0,then
	bl_='Bleche t = '
	*if,arg1,eq,1,then
		bl_='Naehte a = '
	*endif
*elseif,englisch_,eq,1,then
	bl_='Plates t = '
	*if,arg1,eq,1,then
		bl_='Welds a = '
	*endif
*elseif,englisch_,eq,2,then
	bl_='Plaques t = '
	*if,arg1,eq,1,then
		bl_='Soudures a = '
	*endif
*endif

!max. Sectype ermitteln
*get,eanz_,elem,,count
*do,i,1,9999
	esel,u,sec,,i
	*get,eanz_2,elem,,count
	  *if,eanz_2,lt,eanz_,then
		smin_=i
		eanz_=-1
	  *endif
	  *if,eanz_2,eq,0,then
		smax_=i
		*exit
	  *endif
*enddo

cmsel,s,di7_

!Blechdicken ermitteln
*set,vec1
*dim,vec1,,smax_-smin_+1
*set,vec2
*dim,vec2,,smax_-smin_+1

j=1
*do,i,smin_,smax_
	n1=0
	esel,s,sec,,i
	esel,r,ename,,181
	*get,eanz_3,elem,,count
	*if,eanz_3,le,0,cycle
	*get,ielem_,elem,,num,min
	*get, etyp_, elem, ielem_, attr, type
	*get, enam_,etyp,etyp_, attr,enam
	*if,enam_,ne,181,then
		vec2(j)=0
		*else
		*get,n1,shel,i,prop,tthk
		vec1(j)=i
		vec2(j)=n1
		j=j+1
	*endif
*enddo

!der Dicke nach sortieren
*do,i,1,smax_-smin_+1
	*do,j,i+1,smax_-smin_+1
		*if,vec2(i),gt,vec2(j),then
			ii=vec1(i)
			vec1(i)=vec1(j)
			vec1(j)=ii
			ii=vec2(i)
			vec2(i)=vec2(j)
			vec2(j)=ii
		*endif
	*enddo
*enddo

!darstellen
/anno,dele
cmsel,s,di8_
ilast=0.2
jj=1

*do,i,1,smax_-smin_+1
	cmsel,s,di7_
	/trlcy,elem,1
	!/color,elem,lgra
	/color,elem,blac
	*if,vec2(i),gt,ilast,then
		esel,none
		 *do,j,1,smax_-smin_+1
			   *if,vec2(j),eq,vec2(i),then
				esel,a,sec,,vec1(j)
			   *endif
		 *enddo
		cmse,r,di7_
		/trlcy,elem,0
		*if,jj,le,14,then
			/color,elem,%jj%
			*else
			/color,elem,%jj-14%
		*endif

		*get,n2,elem,,count
		*if,n2,gt,0,then
			n1=vec2(i)*10
			cmse,s,di8_
			/tlab, +1.040,-0.98,%bl_% %n1% mm

			!Subtitles uebernehmen
			c01_='                        '
			c02_='                        '
			c03_='                        '
			c04_='                        '

			c1_='        '
			*get,c1_,active,,title,1,start,1
			*if,c1_,ne,'        ',then
				c01_=c1_
				*get,c1_,active,,title,1,start,9
				c01_=strfill(c01_,c1_,9)
				*get,c1_,active,,title,1,start,17
				c01_=strfill(c01_,c1_,17)
				*get,c1_,active,,title,1,start,25
				c01_=strfill(c01_,c1_,25)
				/tlab, +1.040,-0.745,%c01_%
			*endif

			c1_='        '
			*get,c1_,active,,title,2,start,1
			*if,c1_,ne,'        ',then
				c02_=c1_
				*get,c1_,active,,title,2,start,9
				c02_=strfill(c02_,c1_,9)
				*get,c1_,active,,title,2,start,17
				c02_=strfill(c02_,c1_,17)
				*get,c1_,active,,title,2,start,25
				c02_=strfill(c02_,c1_,25)
				/tlab, +1.040,-0.790,%c02_%
			*endif

			c1_='        '
			*get,c1_,active,,title,3,start,1
			*if,c1_,ne,'        ',then
				c03_=c1_
				*get,c1_,active,,title,3,start,9
				c03_=strfill(c03_,c1_,9)
				*get,c1_,active,,title,3,start,17
				c03_=strfill(c03_,c1_,17)
				*get,c1_,active,,title,3,start,25
				c03_=strfill(c03_,c1_,25)
				/tlab, +1.040,-0.835,%c03_%
			*endif

			c1_='        '
				*get,c1_,active,,title,4,start,1
				*if,c1_,ne,'        ',then
				c04_=c1_
				*get,c1_,active,,title,4,start,9
				c04_=strfill(c04_,c1_,9)
				*get,c1_,active,,title,4,start,17
				c04_=strfill(c04_,c1_,17)
				*get,c1_,active,,title,4,start,25
				c04_=strfill(c04_,c1_,25)
				/tlab, +1.040,-0.880,%c04_%
			*endif

			cm,tbl_%jj%,elem
			jj=jj+1
			cmsel,a,di7_
			eplo
			!/era
			!/aut
			/anno,dele
		*endif
		ilast=vec2(i)
	*endif
*enddo

cmse,s,di7_
cmse,s,di8_
cmde,di7_
cmde,di8_
*set,ranz_
*set,bl_
/trlcy,elem,
/color,defa

!ende _______________________________________name____________________________________
/eof
r2sec
!anfang _______________________________________r2sec____________________________________
!Section aus real Machen
*do,i,1,190
	*get,ttt,rcon,i,const,1
	*if,ttt,ge,0.00001,then
		sectype,i,shell,,%i%
		secdata,ttt
	*endif
*enddo
!ende _______________________________________name____________________________________
/eof
Chr2sec
!anfang _______________________________________Chr2sec____________________________________
!real-section überprüfen
*do,i,1,99
	esel,s,real,,i
	*get,emax,elem,,num,max

	*if,emax,ne,0,then
		*get,nn1,elem,emax,attr,real
		*get,nn2,elem,emax,attr,secn

		*get,tt1,rcon,nn1,const,1
		*get,tt2,SHEL,nn2,prop,tthk

		  *if,abs(nn1-nn2),gt,0.1,then
			  *msg,ui,i
			  fehler bei i = %i
		  *endif

		  *if,abs(tt1-tt2),gt,0.1,then
			  *msg,ui,i
			  fehler bei i = %i
		  *endif
	*endif
*enddo
!ende _______________________________________name____________________________________
/eof
dls
!anfang _______________________________________dls____________________________________
	/sys,del *.lis
	/sys,del *.csv
	/sys,del *.txt
!ende _______________________________________name____________________________________
/eof
smisc1
!anfang _______________________________________smisc1____________________________________
	etable,fxi,smisc,1
	plls,fxi,fxi,arg1
	ssum
!ende _______________________________________name____________________________________
/eof
nmisc1
!anfang _______________________________________nmisc1____________________________________
	etable,fxi,nmisc,1
	plls,fxi,fxi,arg1
	ssum
!ende _______________________________________name____________________________________
/eof
di78all
!anfang _______________________________________di78all____________________________________
!nur in Post1 !
*get,rou_,active,,rout
*if,rou_,eq,31,then

	/nopr
	/plopts,info,on
	tsize_=0.8
	/tspec,15,tsize_,1,0,0
	/anno,tmod,1
	/anum,1

	cm,ee_,elem
	cm,nn_,node

	!deutsch / englisch
	*if,englisch_,lt,0.001,then
		englisch_=0
	*endif

	!max. Sectype ermitteln
	*get,eanz_,elem,,count
	*do,i,1,9999
		esel,u,sec,,i
		*get,eanz_2,elem,,count
		*if,eanz_2,lt,eanz_,then
			smin_=i
			eanz_=-1
		*endif
		*if,eanz_2,eq,0,then
			smax_=i
			*exit
		*endif
	*enddo
	r1_=smax_
	*set,vc3_
	*dim,vc3_,,smax_-smin_

	*do,i,smin_,smax_
		vc3_(i)=999999
		cmsel,s,ee_
		esel,r,sec,,i
		*get,e1_,elem,,count
		*if,e1_,gt,0,then
			vc3_(i)=0
			*get,vc3_(i),shel,i,prop,tthk
			vc3_(i)=-1*vc3_(i)*10
		*endif
	*enddo

	!verschiedene Elementdicken suchen
	*set,vc2_
	*dim,vc2_,smax_-smin_
	*do,i,1,smax_-smin_
		vc2_(i)=999999
	*enddo

	nv=0
	*do,i,1,r1_
		*if,vc3_(i),lt,999999,then
			*if,nv,eq,0,then
				nv=nv+1
				vc2_(nv)=vc3_(i)
			*endif
			nvn=0
			*do,j,1,nv
				*if,vc3_(i),eq,vc2_(j),then
					nvn=1
				*endif
			*enddo
			*if,nvn,eq,0,then
				nv=nv+1
				vc2_(nv)=vc3_(i)
			*endif
		*endif
	*enddo

	!Elementdicken sortieren
	*do,i,1,nv-1
		*do,j,i+1,nv
			*if,vc2_(i),gt,vc2_(j),then
				ii=vc2_(i)
				vc2_(i)=vc2_(j)
				vc2_(j)=ii
			*endif
		*enddo
	*enddo

	cmsel,s,ee_
	*get,emin_,elem,,num,min
	*get,emax_,elem,,num,max
	*get,eanz_,elem,,count

	*set,vec_
	*dim,vec_,,emax_
	etable,ddd,smisc,1

	ii=emin_
	*do,i,1,eanz_
		vec_(ii)=0
		*get,rc1_,elem,ii,attr,real
		vec_(ii)=vc3_(rc1_)
		*get,ii,elem,ii,nxth
	*enddo

	*vput,vec_(1),elem,1,etab,ddd

	*if,nv,eq,0,then
		/cval,1,
	*elseif,nv,eq,1
		/cval,1,vc2_(1)
	*elseif,nv,eq,2
		/cval,1,vc2_(1),vc2_(2)
	*elseif,nv,eq,3
		/cval,1,vc2_(1),vc2_(2),vc2_(3)
	*elseif,nv,eq,4
		/cval,1,vc2_(1),vc2_(2),vc2_(3),vc2_(4)
	*elseif,nv,eq,5
		/cval,1,vc2_(1),vc2_(2),vc2_(3),vc2_(4),vc2_(5)
	*elseif,nv,eq,6
		/cval,1,vc2_(1),vc2_(2),vc2_(3),vc2_(4),vc2_(5),vc2_(6)
	*elseif,nv,eq,7
		/cval,1,vc2_(1),vc2_(2),vc2_(3),vc2_(4),vc2_(5),vc2_(6),vc2_(7)
	*else
		/cval,1,vc2_(1),vc2_(2),vc2_(3),vc2_(4),vc2_(5),vc2_(6),vc2_(7),vc2_(nv)
	*endif

	/anno,dele
	/tlabel, +1.040,-0.98,Contact Normal Stiffness

	/anno,refr
	pletab,ddd
	/anno,dele
	/cval

	*set,vec_
	*set,vc2_
*endif
!ende _______________________________________name____________________________________
/eof
wpy
!anfang _______________________________wpy____________________________________________
	!larger working plane display
	wpstyl,,100,-1000,1000,,,0,1
!ende _____________________________________________________________________________
/eof
wpn
!anfang _______________________________wpn____________________________________________
	!default working plane display
	wpstyl,defa
!ende _____________________________________________________________________________
/eof
bdPlot
!anfang _______________________________________bdplot____________________________________
!nur in Post1
*get,rou_,active,,rout
*if,rou_,eq,31,then

	/nopr
	/plopts,info,on
	tsize_=0.8
	/tspec,15,tsize_,1,0,0
	/anno,tmod,1
	/anum,1

	cm,ee1_,elem
	cm,nn1_,node
	esel,r,ename,,188
	nsle
	cm,ee_,elem
	cm,nn_,node

	!deutsch / englisch
	*if,englisch_,lt,0.001,then
		englisch_=0
	*endif

	*get,elemNum,elem,,count
	*get,elemMin,elem,,num,min
	*get,emax_,elem,,num,max

	r1_=300
	*set,vc3_
	*dim,vc3_,,emax_

	*do,i,1,elemNum

		*get,rNum_,elem,elemMin,attr,secn
		*get,rVal_,secp,rNum_,prop,area
		rVal_=nint(sqrt(4*rVal_/3.1416)*10)/10

		vc3_(elemMin)=rVal_
		*get,elemMin,elem,elemMin,nxth

	*enddo

	!verschiedene Elementdicken suchen
	*set,vc2_
	*dim,vc2_,,300
	*do,i,1,300
		vc2_(i)=0
	*enddo

	nv=0
	*get,elemMin,elem,,num,min
	*do,i,1,elemNum
		*if,vc3_(elemMin),gt,0,then
			*if,nv,eq,0,then
				nv=nv+1
				vc2_(nv)=vc3_(elemMin)
			*endif
			nvn=0
			*do,j,1,nv
				*if,vc3_(elemMin),eq,vc2_(j),then
					nvn=1
				*endif
			*enddo
			*if,nvn,eq,0,then
				nv=nv+1
				vc2_(nv)=vc3_(elemMin)
			*endif
		*endif

		*get,elemMin,elem,elemMin,nxth

	*enddo

	!Elementdicken sortieren
	*do,i,1,nv-1
		*do,j,i+1,nv
			*if,vc2_(i),gt,vc2_(j),then
				ii=vc2_(i)
				vc2_(i)=vc2_(j)
				vc2_(j)=ii
			*endif
		*enddo
	*enddo

	cmsel,s,ee_
	*get,emin_,elem,,num,min
	*get,emax_,elem,,num,max
	*get,eanz_,elem,,count

	etable,ddd,smisc,1

	*vput,vc3_(1),elem,1,etab,ddd

	*if,nv,eq,0,then
		/cval,1,
	*elseif,nv,eq,1
		/cval,1,vc2_(1)
	*elseif,nv,eq,2
		/cval,1,vc2_(1),vc2_(2)
	*elseif,nv,eq,3
		/cval,1,vc2_(1),vc2_(2),vc2_(3)
	*elseif,nv,eq,4
		/cval,1,vc2_(1),vc2_(2),vc2_(3),vc2_(4)
	*elseif,nv,eq,5
		/cval,1,vc2_(1),vc2_(2),vc2_(3),vc2_(4),vc2_(5)
	*elseif,nv,eq,6
		/cval,1,vc2_(1),vc2_(2),vc2_(3),vc2_(4),vc2_(5),vc2_(6)
	*elseif,nv,eq,7
		/cval,1,vc2_(1),vc2_(2),vc2_(3),vc2_(4),vc2_(5),vc2_(6),vc2_(7)
	*else
		/cval,1,vc2_(1),vc2_(2),vc2_(3),vc2_(4),vc2_(5),vc2_(6),vc2_(7),vc2_(nv)
	*endif

	/anno,dele
	/tlabel, +1.040,-0.98,Beam Diameter

	/anno,refr
	pletab,ddd
	/anno,dele
	/cval
	/go

	*set,vc2_
	*set,vc3_
*endif
!ende _______________________________________name____________________________________
/eof
baPlot
!anfang _______________________________________baplot____________________________________
!nur in Post1
*get,rou_,active,,rout
*if,rou_,eq,31,then

	/nopr
	/plopts,info,on
	tsize_=0.8
	/tspec,15,tsize_,1,0,0
	/anno,tmod,1
	/anum,1

	cm,ee1_,elem
	cm,nn1_,node
	esel,r,ename,,188
	nsle
	cm,ee_,elem
	cm,nn_,node

	!deutsch / englisch
	*if,englisch_,lt,0.001,then
		englisch_=0
	*endif

	*get,elemNum,elem,,count
	*get,elemMin,elem,,num,min
	*get,emax_,elem,,num,max

	r1_=300
	*set,vc3_
	*dim,vc3_,,emax_

	*do,i,1,elemNum

		*get,rNum_,elem,elemMin,attr,secn
		*get,rVal_,secp,rNum_,prop,area
		!rVal_=nint(sqrt(4*rVal_/3.1416)*10)/10

		vc3_(elemMin)=rVal_
		*get,elemMin,elem,elemMin,nxth

	*enddo

	!verschiedene Elementdicken suchen
	*set,vc2_
	*dim,vc2_,,300
	*do,i,1,300
		vc2_(i)=0
	*enddo

	nv=0
	*get,elemMin,elem,,num,min
	*do,i,1,elemNum
		*if,vc3_(elemMin),gt,0,then
			*if,nv,eq,0,then
				nv=nv+1
				vc2_(nv)=vc3_(elemMin)
			*endif
			nvn=0
			*do,j,1,nv
				*if,vc3_(elemMin),eq,vc2_(j),then
					nvn=1
				*endif
			*enddo
			*if,nvn,eq,0,then
				nv=nv+1
				vc2_(nv)=vc3_(elemMin)
			*endif
		*endif

		*get,elemMin,elem,elemMin,nxth

	*enddo

	!Elementdicken sortieren
	*do,i,1,nv-1
		*do,j,i+1,nv
			*if,vc2_(i),gt,vc2_(j),then
				ii=vc2_(i)
				vc2_(i)=vc2_(j)
				vc2_(j)=ii
			*endif
		*enddo
	*enddo

	cmsel,s,ee_
	*get,emin_,elem,,num,min
	*get,emax_,elem,,num,max
	*get,eanz_,elem,,count

	etable,ddd,smisc,1

	*vput,vc3_(1),elem,1,etab,ddd

	*if,nv,eq,0,then
		/cval,1,
	*elseif,nv,eq,1
		/cval,1,vc2_(1)
	*elseif,nv,eq,2
		/cval,1,vc2_(1),vc2_(2)
	*elseif,nv,eq,3
		/cval,1,vc2_(1),vc2_(2),vc2_(3)
	*elseif,nv,eq,4
		/cval,1,vc2_(1),vc2_(2),vc2_(3),vc2_(4)
	*elseif,nv,eq,5
		/cval,1,vc2_(1),vc2_(2),vc2_(3),vc2_(4),vc2_(5)
	*elseif,nv,eq,6
		/cval,1,vc2_(1),vc2_(2),vc2_(3),vc2_(4),vc2_(5),vc2_(6)
	*elseif,nv,eq,7
		/cval,1,vc2_(1),vc2_(2),vc2_(3),vc2_(4),vc2_(5),vc2_(6),vc2_(7)
	*else
		/cval,1,vc2_(1),vc2_(2),vc2_(3),vc2_(4),vc2_(5),vc2_(6),vc2_(7),vc2_(nv)
	*endif

	/anno,dele
	/tlabel, +1.040,-0.98,Beam Diameter

	/anno,refr
	pletab,ddd
	/anno,dele
	/cval
	/go

	*set,vc2_
	*set,vc3_
*endif
!ende _______________________________________name____________________________________
/eof
laPlot
!anfang _______________________________________laplot____________________________________

	esel,r,ename,,180
	etable,ddd,smisc,2

	/anno,dele
	/tlabel, +1.040,-0.98,Link Area
	/anno,refr
	pletab,ddd
	/anno,dele

!ende _______________________________________name____________________________________
/eof
epll
!anfang _______________________________________epll____________________________________
	esel,s,ename,,180
	esel,a,ename,,188
	*get,rou_,active,,rout
	*if,rou_,eq,31,then
		*if,englisch_,eq,0,then
			/tlabel, +1.040,-0.935,plastische Dehnungen
		*elseif,englisch_,eq,1,then
			/tlabel, +1.040,-0.935,plastic strains
		*endif
		etable,leppl,leppl,1
		plls,leppl,leppl,arg2
		*set,leppl
	*else
		/tlabel, +1.040,-0.935,Go to Post1 to plot Results
		eplo
	*endif
!ende _______________________________________name____________________________________
/eof
esn
!anfang _______________________________________esn____________________________________
	*if,arg2,ge,1,then
		esel,a,ename,,arg1
	*else
		esel,s,ename,,arg1
	*endif
	nsle
!ende _______________________________________esn____________________________________
/eof


